name: Supabase Keep-Alive

on:
  schedule:
    # 毎週日曜日の午前0時 (UTC) に実行
    - cron: '0 0 * * 0'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Supabase
        run: |
          curl -X GET \
            "${{ secrets.SUPABASE_URL }}/rest/v1/profiles?select=*&limit=1" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" 