name: Keep Supabase Alive

on:
  schedule:
    # 毎日 UTC の 18時0分に実行 (日本時間午前3時)
    - cron: '0 18 * * *'
  workflow_dispatch: # 手動実行も可能にする

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase API
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/rest/v1/profiles?select=*" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" 